'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WSApGp
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WSApGpSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WSApGp
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private DeleteAportanteEnGrupoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Datos.My.MySettings.Default.Datos_WSApGp_WSApGp
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event DeleteAportanteEnGrupoCompleted As DeleteAportanteEnGrupoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteAportanteEnGrupo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DeleteAportanteEnGrupo(ByVal aportanteXGrupo As AportantesXGrupoDTO) As Boolean
            Dim results() As Object = Me.Invoke("DeleteAportanteEnGrupo", New Object() {aportanteXGrupo})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DeleteAportanteEnGrupoAsync(ByVal aportanteXGrupo As AportantesXGrupoDTO)
            Me.DeleteAportanteEnGrupoAsync(aportanteXGrupo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteAportanteEnGrupoAsync(ByVal aportanteXGrupo As AportantesXGrupoDTO, ByVal userState As Object)
            If (Me.DeleteAportanteEnGrupoOperationCompleted Is Nothing) Then
                Me.DeleteAportanteEnGrupoOperationCompleted = AddressOf Me.OnDeleteAportanteEnGrupoOperationCompleted
            End If
            Me.InvokeAsync("DeleteAportanteEnGrupo", New Object() {aportanteXGrupo}, Me.DeleteAportanteEnGrupoOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteAportanteEnGrupoOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteAportanteEnGrupoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteAportanteEnGrupoCompleted(Me, New DeleteAportanteEnGrupoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AportantesXGrupoDTO
        
        Private idGrupoField As Integer
        
        Private rutAportanteField As String
        
        Private nombreGrupoField As String
        
        Private nombreAportanteField As String
        
        Private estadoField As Integer
        
        Private fechaIngresoField As System.Nullable(Of Date)
        
        Private usuarioIngresoField As String
        
        Private fechaModificacionField As Date
        
        Private usuarioModificacionField As String
        
        '''<remarks/>
        Public Property IdGrupo() As Integer
            Get
                Return Me.idGrupoField
            End Get
            Set
                Me.idGrupoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RutAportante() As String
            Get
                Return Me.rutAportanteField
            End Get
            Set
                Me.rutAportanteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreGrupo() As String
            Get
                Return Me.nombreGrupoField
            End Get
            Set
                Me.nombreGrupoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreAportante() As String
            Get
                Return Me.nombreAportanteField
            End Get
            Set
                Me.nombreAportanteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Estado() As Integer
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property FechaIngreso() As System.Nullable(Of Date)
            Get
                Return Me.fechaIngresoField
            End Get
            Set
                Me.fechaIngresoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsuarioIngreso() As String
            Get
                Return Me.usuarioIngresoField
            End Get
            Set
                Me.usuarioIngresoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaModificacion() As Date
            Get
                Return Me.fechaModificacionField
            End Get
            Set
                Me.fechaModificacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsuarioModificacion() As String
            Get
                Return Me.usuarioModificacionField
            End Get
            Set
                Me.usuarioModificacionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub DeleteAportanteEnGrupoCompletedEventHandler(ByVal sender As Object, ByVal e As DeleteAportanteEnGrupoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DeleteAportanteEnGrupoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
End Namespace
